name: Non-prod workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
            
      - name: Code quality checks
        run: |
          echo "TODO: This step should check code format and spot bugs."
      
  print-branch-and-file-count:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print Branch Name
        run: |
          echo "Branch name: ${{ github.ref }}"
      
      - name: Count HTML Files
        run: |
          file_count=$(find . -type f -name "*.html" | wc -l)
          echo "Number of .html files in this repo: $file_count"

  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Assume IAM role
        id: assume-role
        run: |
          echo "TODO: assume IAM role and list S3 buckets"