name: Prod workflow

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count HTML files
        run: |
          file_count=$(find . -type f -name "*.html" | wc -l)
          echo "Number of .html files in this repo: $file_count"
